# Generated by Django 5.2.9 on 2025-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='url',
            field=models.URLField(blank=True, help_text='Optional URL to the source', max_length=2000, null=True),
        ),
    ]
